skip_branch_with_pr: true

image:
  - Visual Studio 2017
  - ubuntu

cache:
  - c:\tools\vcpkg\installed\

install:
  - pwsh: |
      if ($isLinux) {
        ./install.linux.ps1
      } else {
        ./install.windows.ps1
      }

build_script:
  - pwsh: |
      if ($isLinux) {
        ./build.linux.ps1
        ./link.linux.ps1
      } else {
        c:\tools\vcpkg\vcpkg.exe install openssl:x64-windows openssl:x86-windows zlib:x64-windows zlib:x86-windows
        .\build.windows.ps1 -VcpkgToolchain c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake
        .\link.windows.ps1
      }

after_build:
  - pwsh:
      if ($isLinux) {
        ./pack.linux.ps1
      } else {
        .\pack.windows.ps1
      }

artifacts:
  - path: tdlib.windows.zip
    name: tdlib.windows
  - path: tdlib.linux.zip
    name: tdlib.linux

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  auth_token: $(TRAVIS_GITHUB_TOKEN)
  artifact: tdlib.windows,tdlib.linux
  on:
    APPVEYOR_REPO_TAG: true
  
