language: cpp

matrix:
  include:
    - os: osx
    - os: linux
    - os: windows


before_install:
        - bash <(wget -O - https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh)
        - if [ "$TRAVIS_OS_NAME" == "osx" ] || [ "$TRAVIS_OS_NAME" == "linux" ] ; then  pwsh ./install.$TRAVIS_OS_NAME.ps1; fi
        - if [ "$TRAVIS_OS_NAME" == "windows" ] ; then  powershell ./install.$TRAVIS_OS_NAME.ps1; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] || [ "$TRAVIS_OS_NAME" == "linux" ] ;  then pwsh ./build.$TRAVIS_OS_NAME.ps1; pwsh ./pack.$TRAVIS_OS_NAME.ps1; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ] ; then powershell ./build.$TRAVIS_OS_NAME.ps1; powershell ./pack.$TRAVIS_OS_NAME.ps1; fi

deploy:
  provider: releases
  api_key: 
    - secure: $TRAVIS_GITHUB_TOKEN
  file:
    - tdlib.$TRAVIS_OS_NAME.zip
  skip_cleanup: true
  on:
    tags: true
