language: cpp

matrix:
  include:
    - os: osx


before_install:
        - bash <(wget -O - https://raw.githubusercontent.com/PowerShell/PowerShell/master/tools/install-powershell.sh)
        - pwsh ./install.$TRAVIS_OS_NAME.ps1

script:
  - pwsh ./build.$TRAVIS_OS_NAME.ps1
  - pwsh ./pack.$TRAVIS_OS_NAME.ps1

deploy:
  provider: releases
  api_key: 
    - secure: $TRAVIS_GITHUB_TOKEN
  file:
    - tdlib.$TRAVIS_OS_NAME.zip
  skip_cleanup: true
  on:
    tags: true
